<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Hobbies</name>
   <tag></tag>
   <elementGuidId>e6bc3848-4999-4e05-a547-dff322f4d371</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.chakra-checkbox__control.css-5190u4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[4]/div/div/form/div/div/div[7]/div[2]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label >> internal:has-text=&quot;Sports&quot;i >> span >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c73aede8-13c4-4889-8ec3-f7e49f13c966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-checkbox__control css-5190u4</value>
      <webElementGuid>eca06899-17d4-4a0c-afe3-603b8f7d15ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4afc3b6a-7817-4be6-bca8-6f2a46d8552d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-1brywh5&quot;]/div[@class=&quot;css-1l2oahx&quot;]/div[@class=&quot;css-5iccig&quot;]/div[@class=&quot;css-exzcdt&quot;]/div[@class=&quot;css-1s5ocgd&quot;]/form[1]/div[@class=&quot;css-h9t2jw&quot;]/div[@class=&quot;chakra-stack css-ylp6it&quot;]/div[@class=&quot;chakra-form-control css-1kxonj9&quot;]/div[@class=&quot;css-0&quot;]/label[@class=&quot;chakra-checkbox css-vnk8db&quot;]/span[@class=&quot;chakra-checkbox__control css-5190u4&quot;]</value>
      <webElementGuid>5c279066-9bcf-4281-92ce-005442b3a430</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[4]/div/div/form/div/div/div[7]/div[2]/label/span</value>
      <webElementGuid>9e4ae141-e1eb-4dc4-9eaa-6de638f66063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[5]/following::span[2]</value>
      <webElementGuid>508b0d51-9f73-4d63-b922-4ef4bb208dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sports'])[1]/preceding::span[1]</value>
      <webElementGuid>24830dab-11b8-4968-bd36-f3edce33b113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Music'])[1]/preceding::span[3]</value>
      <webElementGuid>ef3b1c58-fe3b-44eb-98ff-43452d59b66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/label/span</value>
      <webElementGuid>92034f3c-9db7-485a-9f26-a66b5b84386f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
