<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name</name>
   <tag></tag>
   <elementGuidId>c9c88565-e6b0-45e8-9234-ce09e7248ef9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#64532b696a6af30013dc8321</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='64532b696a6af30013dc8321']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;2. Last Name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51a36392-63e2-4ab2-942a-d880c4a30ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>2. Last Name</value>
      <webElementGuid>2ef6e32a-0a64-42a0-bd91-916151778ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>64532b696a6af30013dc8321</value>
      <webElementGuid>2b94a814-7cf7-4f66-b9b6-e92c9d0c563c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>64532b696a6af30013dc8321</value>
      <webElementGuid>f6097861-4029-450e-ace8-1e13ab501ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ddc0bda2-6655-4767-a5c9-4ec8a3928091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-188tka1</value>
      <webElementGuid>12b7ffaa-b9e6-4169-8706-5ee01873bf8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;64532b696a6af30013dc8321&quot;)</value>
      <webElementGuid>f60850a6-04cf-4812-bb56-5bd4058ae72f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='64532b696a6af30013dc8321']</value>
      <webElementGuid>996a239b-c1c4-4ea1-b2c2-019b16341888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[4]/div/div/form/div/div/div[2]/input</value>
      <webElementGuid>0de5c543-46b0-4add-a973-9a150c816e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>721d1887-85d7-4946-9cf6-80244528ebc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '64532b696a6af30013dc8321' and @id = '64532b696a6af30013dc8321']</value>
      <webElementGuid>e4d7a5c4-7390-4607-8e87-ddad43a268c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
