<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile number</name>
   <tag></tag>
   <elementGuidId>87ef385a-4fa4-44e4-b1bb-ec3394573582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#6453527335eb0c00128fbabf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='6453527335eb0c00128fbabf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;8123 4567&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d2a0fe0-1157-4451-b317-d40b9d423059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>8123 4567</value>
      <webElementGuid>3624f5df-aa7c-4ace-ba20-1404eacdbd73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>2223cf66-eb03-4804-92c4-91ccedcab478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>6453527335eb0c00128fbabf</value>
      <webElementGuid>9282075a-4413-455d-8c5f-0cdd4aed8d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6453527335eb0c00128fbabf</value>
      <webElementGuid>decc880a-d424-44b9-b709-d257f081c18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>01b25305-b85d-4371-a60f-c1bc4727488f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-nc2kb1</value>
      <webElementGuid>3656aba6-f3cc-46ca-b1a5-aff6c673c122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6453527335eb0c00128fbabf&quot;)</value>
      <webElementGuid>8374e4b4-3cc0-4662-aa7f-895181df14cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='6453527335eb0c00128fbabf']</value>
      <webElementGuid>d6328381-8f57-419e-aa0e-dbcc87276c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[4]/div/div/form/div/div/div[5]/div[2]/input</value>
      <webElementGuid>2f01bfc7-3dd6-43a2-918b-e676c0efdc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>cbce14ba-cd1f-44d4-80ea-df963e89ab4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '8123 4567' and @name = '6453527335eb0c00128fbabf' and @id = '6453527335eb0c00128fbabf']</value>
      <webElementGuid>095848a4-9b85-4329-af16-f57a08bf6134</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
