<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Address(optional)</name>
   <tag></tag>
   <elementGuidId>51f03f94-dce1-4bbb-a6c2-15897b612010</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#6453553781cb0e001299cc83</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='6453553781cb0e001299cc83']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;10. Address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d4ed01f3-fd67-49e2-bcbc-07bcc93eb666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>10. Address</value>
      <webElementGuid>4cd92b33-bad7-4601-a406-b17d46f0df60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>6453553781cb0e001299cc83</value>
      <webElementGuid>4b0ae1d9-b55c-48e4-acca-2391d1b55e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6453553781cb0e001299cc83</value>
      <webElementGuid>82cac470-9753-423c-bf35-441f6821f61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-textarea css-8q1ttb</value>
      <webElementGuid>246d15d7-ffdf-4d60-895d-e2f39864373c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6453553781cb0e001299cc83&quot;)</value>
      <webElementGuid>a09ab2aa-d33d-480d-bf83-71f809842567</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='6453553781cb0e001299cc83']</value>
      <webElementGuid>3c3b1368-6ca1-442e-a438-8531adeb706b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[4]/div/div/form/div/div/div[10]/textarea</value>
      <webElementGuid>f2b3c25b-0a44-4993-b5ff-585c265bb2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>97411cd8-0d34-47db-a6cc-26db47522688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = '6453553781cb0e001299cc83' and @id = '6453553781cb0e001299cc83']</value>
      <webElementGuid>a219c7c5-b9ff-4bfc-9237-1ed52c3efd62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
